# Generated by Django 5.2 on 2025-05-26 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "openmrs_patient_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "patient_id",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="환자번호"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="이름")),
                ("birth_date", models.DateField(verbose_name="생년월일")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "남성"), ("F", "여성"), ("O", "기타")],
                        max_length=1,
                        verbose_name="성별",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="전화번호"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="이메일"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="주소")),
                (
                    "blood_type",
                    models.CharField(blank=True, max_length=5, verbose_name="혈액형"),
                ),
                ("allergies", models.TextField(blank=True, verbose_name="알레르기")),
                ("medical_history", models.TextField(blank=True, verbose_name="병력")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="등록자",
                    ),
                ),
            ],
            options={
                "verbose_name": "환자",
                "verbose_name_plural": "환자",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "openmrs_visit_id",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                (
                    "visit_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="방문번호"
                    ),
                ),
                (
                    "visit_type",
                    models.CharField(
                        choices=[
                            ("OUTPATIENT", "외래"),
                            ("INPATIENT", "입원"),
                            ("EMERGENCY", "응급"),
                        ],
                        max_length=20,
                        verbose_name="방문유형",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "예약"),
                            ("IN_PROGRESS", "진료중"),
                            ("COMPLETED", "완료"),
                            ("CANCELLED", "취소"),
                        ],
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                ("visit_date", models.DateTimeField(verbose_name="방문일시")),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="종료일시"
                    ),
                ),
                (
                    "department",
                    models.CharField(blank=True, max_length=100, verbose_name="진료과"),
                ),
                (
                    "chief_complaint",
                    models.TextField(blank=True, verbose_name="주호소"),
                ),
                ("diagnosis", models.TextField(blank=True, verbose_name="진단")),
                (
                    "treatment_plan",
                    models.TextField(blank=True, verbose_name="치료계획"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="특이사항")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "attending_doctor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="담당의",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.patient",
                        verbose_name="환자",
                    ),
                ),
            ],
            options={
                "verbose_name": "방문",
                "verbose_name_plural": "방문",
                "ordering": ["-visit_date"],
            },
        ),
        migrations.CreateModel(
            name="VitalSigns",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "systolic_bp",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="수축기혈압"
                    ),
                ),
                (
                    "diastolic_bp",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="이완기혈압"
                    ),
                ),
                (
                    "heart_rate",
                    models.IntegerField(blank=True, null=True, verbose_name="심박수"),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="체온",
                    ),
                ),
                (
                    "respiratory_rate",
                    models.IntegerField(blank=True, null=True, verbose_name="호흡수"),
                ),
                (
                    "oxygen_saturation",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="산소포화도"
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="키(cm)",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="체중(kg)",
                    ),
                ),
                (
                    "measured_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="측정시간"),
                ),
                (
                    "measured_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="측정자",
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="patients.visit",
                        verbose_name="방문",
                    ),
                ),
            ],
            options={
                "verbose_name": "활력징후",
                "verbose_name_plural": "활력징후",
                "ordering": ["-measured_at"],
            },
        ),
    ]
