# Generated by Django 5.2 on 2025-05-29 05:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="vitalsigns",
            name="measured_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="patient_vitalsigns",
                to=settings.AUTH_USER_MODEL,
                verbose_name="측정자",
            ),
        ),
    ]
