# Generated by Django 4.2 on 2025-06-11 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalsigns',
            name='measured_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_vitalsigns', to=settings.AUTH_USER_MODEL, verbose_name='측정자'),
        ),
    ]
