global:
  scrape_interval: 15s

scrape_configs:
  # Prometheus 자체 모니터링
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Django 앱 (Prometheus Django exporter 필요)
  - job_name: 'django'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: /metrics   # Django exporter endpoint (예: django-prometheus)

  # Redis (redis_exporter 필요할 수도 있음)
  - job_name: 'redis'
    static_configs:
      - targets: ['host.docker.internal:6379']
    metrics_path: /metrics   # redis_exporter 사용 시, 기본: :9121

  # PostgreSQL (Postgres exporter 사용)
  - job_name: 'postgresql'
    static_configs:
      - targets: ['host.docker.internal:9187']
    metrics_path: /metrics   # postgres_exporter 기본 endpoint

  # OpenMRS (JMX exporter 등 활용)
  - job_name: 'openmrs'
    static_configs:
      - targets: ['host.docker.internal:8080']
    metrics_path: /actuator/prometheus  # spring-actuator 사용시

# 필요시 job_name, metrics_path 등 서비스 환경에 맞게 조정