# Generated by Django 4.2 on 2025-06-11 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cdss', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalrule',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cdss_rules', to=settings.AUTH_USER_MODEL, verbose_name='생성자'),
        ),
        migrations.AlterField(
            model_name='diagnosissupport',
            name='analyzed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosis_supports', to=settings.AUTH_USER_MODEL, verbose_name='요청의사'),
        ),
    ]
