# Generated by Django 5.2 on 2025-05-29 08:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OpenMRSPatient",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="OpenMRS Patient UUID",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "display",
                    models.CharField(
                        help_text="OpenMRS Patient display (e.g., ID - Name)",
                        max_length=255,
                    ),
                ),
                (
                    "identifier",
                    models.CharField(
                        blank=True,
                        help_text="OpenMRS ID (예: 10001V)",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("given_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "family_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("gender", models.CharField(blank=True, max_length=10, null=True)),
                ("birthdate", models.DateField(blank=True, null=True)),
                ("last_synced", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "OpenMRS Patient",
                "verbose_name_plural": "OpenMRS Patients",
                "ordering": ["family_name", "given_name"],
            },
        ),
    ]
