# Generated by Django 5.2 on 2025-05-29 08:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openmrs_integration", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="openmrspatient",
            options={
                "ordering": ["family_name", "given_name"],
                "verbose_name": "OpenMRS Patient Record",
                "verbose_name_plural": "OpenMRS Patient Records",
            },
        ),
        migrations.RemoveField(
            model_name="openmrspatient",
            name="display",
        ),
        migrations.RemoveField(
            model_name="openmrspatient",
            name="last_synced",
        ),
        migrations.AddField(
            model_name="openmrspatient",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="openmrspatient",
            name="display_name",
            field=models.CharField(
                blank=True,
                help_text="Patient's full name or display name",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="openmrspatient",
            name="raw_openmrs_data",
            field=models.JSONField(
                blank=True, help_text="Raw patient data from OpenMRS as JSON", null=True
            ),
        ),
        migrations.AddField(
            model_name="openmrspatient",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="openmrspatient",
            name="identifier",
            field=models.CharField(
                blank=True,
                help_text="Primary OpenMRS ID",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="openmrspatient",
            name="uuid",
            field=models.UUIDField(
                editable=False,
                help_text="OpenMRS Patient UUID",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
